dmx:
  fixtures:
    folder: fixtures

  animation:
    max_fps: 43 # Optional

  artnet:
    refresh_every: 1.2 # Optional

    universes:
#      - 1/2/0: # Net = 1 / Sub-net = 2 / Universe = 0
#          devices:
#            - Epic triple lights:
#                start_address: 11
#                fixture: CLHB300RGBW
#                mode: 42ch
#
#          compatibility:
#            send_partial_universe: False
#            manual_nodes:
#              - { host: 192.168.1.11, port: 6454 }
#              - { host: 192.168.1.12 }

#      - 3: # Net and Sub-net default to 0, universe = 3
#          devices:
#            - DJ led:
#                start_address: 0
#                fixture: DJ Scan LED
      - 0/0/20:
          devices:
            - Bureau NO:
                fixture: CW/WW Fader
                start_address: 0
                mode: 16bit-cw
                entity_id_prefix: lol_this_is_prefix
            - Bureau LED strip:
                fixture: CW/WW Fader
                start_address: 247
                mode: 8bit-wc
#  sacn:
#    source_name: "Test SACN source LOL!!"
#    priority: 123
#    enable_preview_data: true
#    universes:
#      - 1:
#          devices:
#            - Test RGBWW fixture:
#                fixture: RGBWW
#                start_address: 1
#                mode: 8bit
#          compatibility:
#            unicast_addresses:
#              - { host: 192.168.1.15 }



#    triggers: # All triggers will always send HA events, regardless if being configured
#      scenes: # Trigger HA scenes FROM external ArtNet controller
#        - 1:
#            scene_entity_id: scene.romantic
#            transition: 2.5
#        - 5:
#            scene_entity_id: scene.movie
#            transition: 0
#
#      shows: # HA trigger show TO external ArtNet controller's
#        - 2:
#            name: Rose # Creates a button entity with this name
#            oem: 4567 # So that the controller knows it's for itself
#            host: 192.168.1.11 # If not defined, will broadcast instead
#
#      text: # Receive ASCII from external
#        name: SuperTextInput # Inputs ASCII text into HA

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning
  logs:
    custom_components.dmx: debug
    custom_components.dmx.client: info
    custom_components.dmx.entity.node_handler: info
    custom_components.dmx.util: debug
    custom_components.dmx.bridge: debug
    custom_components.dmx.server: debug

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
